### ISSUE TITLE
Finetuning Blender3B on 2 parallel 12GB GPUs

### ISSUE THREAD

**Issue by aslu98** [facebookresearch/ParlAI#2969]
Hi, 
I would like to fine tune the Blender3B model but I only have two 12GB gpus (on one single host). 
From what I read here https://parl.ai/projects/recipes/ I would need 32GB to finetune, but I'm not sure if they are needed only when finetuning on blended_skill or on any dataset.

I already tried to lower down `-batchsize ,  --label-truncate,  --text-truncate` and `--truncate` to 1 but I still got `CUDA out of memory.`
My full command with all args is: 
`parlai multiprocessing_train  -t fromfile:parlaiformat \
       --fromfile_datapath ../parlai_utilities/covidQA_parlaiformat.txt -m transformer/generator \
         --init-model zoo:blender/blender_3B/model --dict-file zoo:blender/blender_3B/model.dict \
         -veps 0.25 --attention-dropout 0.0 -bs 1  --embedding-size 2560 \
         --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 \
         --n-encoder-layers 2 --n-decoder-layers 24 \
         --history-add-global-end-token end --delimiter ' ' \
         --dict-tokenizer bytelevelbpe --dropout 0.1 --fp16 True \
         --label-truncate 1 --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau \
         --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu \
  	   --text-truncate 1 --truncate 1 \
         --warmup_updates 100 --fp16-impl mem_efficient --update-freq 2 --gradient-clip 0.1 \
         --skip-generation True -vp 10 -vmt ppl -vmm min \
         --num-epochs 1 --save-after-valid True --model-file covid3B`

I also tried to use `train_model` with `--model-parallel true` as from my understanding of #2962 it should let me train bigger models even if slowly, but I still got `CUDA out of memory`. 
With this setting I couldn't lower under 8 the args I mentioned above: even if I set them to 4, 2 or 1 i got error `CUDA OOM: Lower batch size (-bs) from 8 or lower  max sequence length (-tr) from 8`

Is there anything else I could try or args I could change to get it to work in my environment?

**Comment by stephenroller** [comment]
Try using model parallel and adafactor instead of ADAM. If that doesn’t work, try switching to the SGD with momentum optimizer, which is considerably less memory hungry.

And yes you might need to lower your batch size to 1. Use `—update-freq` for gradient accumulation.

**Comment by aslu98** [comment]
Thank you,
I tried ADAM but it was still "too heavy" but finally with sgd and batchsize 1 it succeeded (at least for 1 test epoch).

If anyone have the same issue the final working command for me is:
`parlai train_model  -t fromfile:parlaiformat \
       --fromfile_datapath ../parlai_utilities/covidQA_parlaiformat.txt -m transformer/generator \
         --init-model zoo:blender/blender_3B/model --dict-file zoo:blender/blender_3B/model.dict \
         -veps 0.25 --attention-dropout 0.0 -bs 1  --embedding-size 2560 \
          --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 \
         --n-encoder-layers 2 --n-decoder-layers 24 \
         --history-add-global-end-token end --delimiter ' ' \
         --dict-tokenizer bytelevelbpe --dropout 0.1 --fp16 True \
         --label-truncate 16 --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau \
         --lr-scheduler-patience 3 --optimizer sgd --relu-dropout 0.0 --activation gelu \
  	   --text-truncate 16 --truncate 8 \
         --warmup_updates 100 --update-freq 2 --gradient-clip 0.1 \
         --model-parallel True --skip-generation True -vp 10 -vmt ppl -vmm min \
         --num-epochs 1.0 --save-after-valid True --model-file covid3B`

Now I'm testing larger `-tr` values as just 8 or 16 is quite useless for my task.
Thank you again, I'm closing the issue.

**Comment by aslu98** [comment]
I've tried many different sets of args, in my last attempts I got a new kind of error, different from CUDA out of memory:

`RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

The command I used is:
`parlai train_model -t fromfile:parlaiformat,blended_skill_talk --fromfile_datapath ../parlai_utilities/covidQA_parlaiformat.txt -m transformer/generator --multitask-weights 2,1 --num-epochs 20.0 --init-model zoo:blender/reddit_3B/model --dict-file zoo:blender/reddit_3B/model.dict --embedding-size 2560 --n-encoder-layers 2 --n-decoder-layers 24 --ffn-size 10240 --dropout 0.1 --n-heads 32 --learn-positional-embeddings True  --n-positions 128 --variant prelayernorm --activation gelu --skip-generation True --fp16 True --text-truncate 256 --label-truncate 256 --dict-tokenizer bpe --dict-lower True -lr 7e-06 --optimizer sgd --momentum 0.9 --lr-scheduler reduceonplateau --gradient-clip 0.1 -veps 0.25 --update-freq 10 --attention-dropout 0.0 --relu-dropout 0.0 --history-add-global-end-token end --delimiter '  ' --skip-generation True -vp 10 -stim 10 -vme 1000 -bs 1 -vmt ppl -vmm min --save-after-valid True --model_parallel True --model-file covid-reddit-blended`

Full traceback:
```
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexTyp
e, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [99,0,0], thread: [125,0,0] Assertion `srcIndex < srcSelectDimSi
ze` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexTyp
e, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [99,0,0], thread: [126,0,0] Assertion `srcIndex < srcSelectDimSi
ze` failed.
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexTyp
e, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [99,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSi
ze` failed.
Traceback (most recent call last):
  File "/usr/local/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/parlai/core/script.py", line 272, in superscript_main
    SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/parlai/core/script.py", line 88, in _run_from_parser_and_opt
    return script.run()
  File "/parlai/scripts/train_model.py", line 770, in run
    return self.train_loop.train()
  File "/parlai/scripts/train_model.py", line 653, in train
    world.parley()
  File "/parlai/core/worlds.py", line 746, in parley
    self.worlds[self.world_idx].parley()
  File "/parlai/core/worlds.py", line 356, in parley
    acts[1] = agents[1].act()
  File "/parlai/core/torch_agent.py", line 1924, in act
    response = self.batch_act([self.observation])[0]
  File "/parlai/core/torch_agent.py", line 1980, in batch_act
    output = self.train_step(batch)
  File "/parlai/core/torch_generator_agent.py", line 769, in train_step
    self._init_cuda_buffer(self.opt['batchsize'], self.label_truncate or 256)
  File "/parlai/core/torch_generator_agent.py", line 670, in _init_cuda_buffer
    raise e
  File "/parlai/core/torch_generator_agent.py", line 656, in _init_cuda_buffer
loss = 0 * self.compute_loss(self._dummy_batch(batchsize, maxlen))
  File "/parlai/core/torch_generator_agent.py", line 739, in compute_loss
    model_output = self.model(*self._model_input(batch), ys=batch.label_vec)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/parlai/core/torch_generator_agent.py", line 324, in forward
    encoder_states = prev_enc if prev_enc is not None else self.encoder(*xs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/parlai/agents/transformer/modules.py", line 597, in forward
    tensor = self.forward_layers(tensor, mask)
  File "/parlai/agents/transformer/modules.py", line 532, in forward_layers
    tensor = self._apply_model_parallel(tensor, mask)
  File "/parlai/agents/transformer/modules.py", line 619, in _apply_model_parallel
    s_tensor = self.layers[layer_no](s_tensor, s_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/parlai/agents/transformer/modules.py", line 667, in forward
    attended_tensor, _ = self.attention(tensor, mask=mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/parlai/agents/transformer/modules.py", line 1336, in forward
    q = prepare_head(self.q_lin(query))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)
```
Before I have many more `Assertion `srcIndex < srcSelectDimSize` failed.` with different `block:` and `thread:`

**Comment by stephenroller** [comment]
The values for the truncate arguments can not exceed the number of positions, so it’s limited to 128. I’ve tried extended the number of positions before (they are sinusoidal embeddings) but found it didn’t work well.

**Comment by Hilal-Urun** [comment]
python3 parlai/scripts/train_model.py -t blended_skill_talk,wikipedia:full --multitask-weights 1,3,3,3 --num-epochs 0.20 -veps 0.05 --attention-dropout 0.0 -bs 1  --model transformer/generator --embedding-size 2560 --ffn-size 10240 --variant prelayernorm --n-heads 32 --n-positions 128 --n-encoder-layers 2 --n-decoder-layers 24 --history-add-global-end-token end --delimiter '  ' --dict-tokenizer bytelevelbpe  --dropout 0.1 --fp16 true --init-model zoo:blender/blender_3B/model --dict-file zoo:blender/blender_3B/model.dict --label-truncate 8  --log_every_n_secs 10 -lr 7e-06 --lr-scheduler reduceonplateau --lr-scheduler-patience 3 --optimizer adam --relu-dropout 0.0 --activation gelu --model-parallel false  --save-after-valid true --text-truncate 8  --truncate 8  --warmup_updates 100 --fp16-impl mem_efficient --update-freq 2 --gradient-clip 0.1 --skip-generation true -vp 10 -vmt ppl -vmm min --model-file parlai/data/test_train_27B


Hi I have same problem and now I have 2x16 gpus and I 2m trying to fine tune blender3B model but it gives run out of memory error and wikipedia data just 232.9 MB, How can I fix the problem , could you help please

**Comment by stephenroller** [comment]
you get a CUDA out of memory error or a RAM one? The wikipedia corpus needs like 40gb of ram to load.

**Comment by Hilal-Urun** [comment]
Yes, thank you so much I fixed the problem

**Comment by stephenroller** [comment]
For the record, you also are missing `--model-parallel true`, which will definitely cuda OOM, as that is just training on 1 GPU.

**Comment by Hilal-Urun** [comment]
Yes, I also added the model parallel true but problem related to the ram like you said. That's why I will increased it.  For now I'm working on blender_90M model and it works :)

**Comment by stephenroller** [comment]
With two 16gb GPUs, I also don't expect `--optimizer adam` to fit in memory. You can use `--optimizer adafactor` though

For the record, I highly recommend sticking to `--label-truncate 128 --text-truncate 128`. With bs=1, two 16gb gpus, and `--model-parallel true --optimizer adafactor`, things worked okay for me.

**Comment by Hilal-Urun** [comment]
Okey, I'm gonna try after working one is finished :) Thanks a lot for information.
