### ISSUE TITLE
CUDA error: device-side assert triggered when I used Bert cross encoder on my own dataset.

### ISSUE THREAD

**Issue by 731935354** [facebookresearch/ParlAI#3005]
**Environment**
* ParlAI: v0.8
* PyTorch: 1.4.1
* Python: 3.7.4
* OS: RedHat
* GPU: Nvidia P100

**Bug description**
CUDA error: device-side assert triggered when I used Bert cross encoder on my own dataset.

**Logs**
```
/usr/local/easybuild-2019/easybuild/build/PyTorch/1.4.0/fosscuda-2019b-Python-3.7.4/pytorch-1.4.0/aten/src/THCUNN/ClassNLLCriterion.cu:57: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [13,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/usr/local/easybuild-2019/easybuild/build/PyTorch/1.4.0/fosscuda-2019b-Python-3.7.4/pytorch-1.4.0/aten/src/THCUNN/ClassNLLCriterion.cu:57: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [14,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/usr/local/easybuild-2019/easybuild/build/PyTorch/1.4.0/fosscuda-2019b-Python-3.7.4/pytorch-1.4.0/aten/src/THCUNN/ClassNLLCriterion.cu:57: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [15,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.

Traceback (most recent call last):
  File "../ParlAI/parlai/core/torch_ranker_agent.py", line 451, in train_step
    self.record_local_metric('mean_loss', AverageMetric.many(loss))
  File "../ParlAI/parlai/core/metrics.py", line 172, in many
    return [cls(*items) for items in zip(*objs)]
  File "../ParlAI/parlai/core/metrics.py", line 172, in <listcomp>
    return [cls(*items) for items in zip(*objs)]
  File "../ParlAI/parlai/core/metrics.py", line 247, in __init__
    self._numer = self.as_number(numer)
  File "../ParlAI/parlai/core/metrics.py", line 148, in as_number
    obj_as_number: Union[int, float] = obj.item()
RuntimeError: CUDA error: device-side assert triggered
```

**Training command**
```
parlai train_model -m bert_ranker/cross_encoder_ranker -t irc_disentanglement --type-optimization additional_layers --num-epochs 10 --batchsize 4 --data-parallel True --label-truncate 60 --text-truncate 60 --candidates batch --dict-tokenizer bpe   --dict-lower True  --optimizer adamax  --fp16 False --model-file tmp/parlai_cross_bert_test/model --update-freq 2
```
Note that **irc_disentanglement** is my own task.
I tried to run only forward pass to make sure my dataset was correctly implemented. It turned out that without back propagation and parameter update, there was no bug reported.

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

Any suggestions will be appreciated!

**Comment by stephenroller** [comment]
device-side asserts are the most generic exception that NVIDIA can give. Try rerunning your command with the environmental variable `CUDA_LAUNCH_BLOCKING=1` set, and then paste the exception again.

**Comment by 731935354** [comment]
I tried to add `export CUDA_LAUNCH_BLOCKING=1` before the training command in the shell script. And there was no more log info after " Executing train mode with batch labels as set of candidates." (I waited for another 20 minutes, still no more logging).  Is it stuck?

Just to clarify, I was using an HPC system from school (not admin). Will it work as expected after I set the environmental variable?

The log was as follows:
```
2020-08-26 10:32:56,984 INFO     | creating task(s): irc_disentanglement
2020-08-26 10:32:58,538 INFO     | training...
2020-08-26 10:32:58,545 WARNING  | [ Executing train mode with batch labels as set of candidates. ]
```

However the training process worked smoothly when I use a different version of pytorch. Though the error is no more a problem for me, I'm still curious about the reason behind.

Thanks very much for your help.

**Comment by stephenroller** [comment]
What version of pytorch worked and what didn’t?

It might be the wrong CUDA version.

**Comment by 731935354** [comment]
Problem solved. Both pytorch 1.5.1 and pytorch 1.4.0 worked for me.
I just run 1 epoch for both pytorch version, they worked smoothly.

I finally found out that when I tried to use pytorch 1.5.1 before (which reported the error), it actually reloaded pytorch 1.4.0 (when I load the apex module provided in HPC). In this case the original problem may result from incompatible pytorch and CUDA, since the reloading process will not change CUDA version.

Thanks very much!
