### ISSUE TITLE
CUDA Out of Memory When Fine-tuning T5-11B

### ISSUE THREAD

**Issue by lyy1994** [facebookresearch/ParlAI#4452]
**Bug description**
I am using ParlAI-1.5.1 release and 8 A100 80G to fine-tune a T5-11B model using model parallelism. I think it should have enough GPU RAM for this model with a batch size of 1, but the CUDA Out of Memory error is raised.

**Reproduction steps**
The command I used is
```
parlai train_model -t wizard_of_wikipedia:generator --add-missing-turns all -m hugging_face/t5 --t5-model-arch t5-11b --t5-model-parallel True -lr 5e-05 --fp16 True --optimizer adam --lr-scheduler invsqrt --warmup-updates 1000 --max-train-steps 200000 --betas 0.9,0.999 --update-freq 64 --skip-generation True -vp 15 -vstep 1000 -bs 1 -vmt ppl -vmm min --tr 256 --model-file ft-hf-t5-11b/t5-11b
```
where the batch size is just 1.

**Logs**

```
2022-03-26 21:01:34,061 INFO     | building dictionary first...
2022-03-26 21:01:34,065 INFO     | No model with opt yet at: ft-hf-t5-11b/t5-11b(.opt)
2022-03-26 21:01:34,068 INFO     | Using CUDA
2022-03-26 21:03:57,284 INFO     | Total parameters: 11,307,321,344 (11,307,321,344 trainable)
Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/bin/parlai", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/__main__.py", line 14, in main
    superscript_main()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 997, in run
    self.train_loop = TrainLoop(self.opt)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 353, in __init__
    self.agent = create_agent(opt)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/agents.py", line 479, in create_agent
    model = model_class(opt)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 525, in __init__
    was_reset = self.init_optim(
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 1056, in init_optim
    self.optimizer = SafeFP16Optimizer(
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/utils/fp16.py", line 114, in __init__
    self.fp32_params = self._build_fp32_params(self.fp16_params, flatten=False)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/utils/fp16.py", line 156, in _build_fp32_params
    p32.grad = torch.zeros_like(p32.data)
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 79.35 GiB total capacity; 77.75 GiB already allocated; 21.19 MiB free; 77.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by stephenroller** [comment]
I'm not 100% it's using MP, but even then 11B should easily fit on one 80gb...

**Comment by lyy1994** [comment]
I think it is using MP because I tested this command (with a smaller t5) on other machines before and it worked fine. I am wondering whether the optimizer does not use MP (initially?), as 80GB RAM might not be sufficient for 11B with an Adam optimizer.

**Comment by klshuster** [comment]
IIRC we load the optimizer onto only the first GPU for MP, so your intuition may be correct here

**Comment by stephenroller** [comment]
Oof. Zero2 is a better choice then

**Comment by klshuster** [comment]
> Oof. Zero2 is a better choice then

https://parl.ai/docs/tutorial_fast.html#use-multiple-gpus with `--ddp-backend zero2`

**Comment by lyy1994** [comment]
I think we can't add `--ddp-backend zero2` as I am using `train_model` instead of `multiprocessing_train` now. Is it possible to have another solution?

**Comment by klshuster** [comment]
can you try with `multiprocessing_train`?

**Comment by lyy1994** [comment]
Thanks for the suggestion! It seems that the model can be successfully loaded into GPU and start training (4 A100). But t5-11b is too large and runs out of memory even with `-bs 1 --tr 8`. Also I notice that the model parameters become 2,826,830,336 instead of 11,307,321,344. I am not sure this is normal using `--ddp-backend zero2` because I am not familiar with it...

```
2022-04-03 18:36:55,919 INFO     | Distributed group initialized
2022-04-03 18:37:03,139 INFO     | building dictionary first...
2022-04-03 18:37:03,147 INFO     | No model with opt yet at: ft-hf-t5-11b/t5-11b(.opt)
2022-04-03 18:37:03,148 INFO     | Using CUDA
2022-04-03 18:42:45,809 INFO     | Total parameters: 2,826,830,336 (2,826,830,336 trainable)
2022-04-03 18:42:45,835 WARNING  | --lr-scheduler invsqrt requires a value for --invsqrt-lr-decay-gamma. Defaulting to set gamma to --warmup-updates value for backwards compatibility.
2022-04-03 18:42:45,836 INFO     | Opt:
2022-04-03 18:42:45,836 INFO     |     adafactor_eps: '(1e-30, 0.001)'
2022-04-03 18:42:45,836 INFO     |     adam_eps: 1e-08
2022-04-03 18:42:45,836 INFO     |     add_missing_turns: all
2022-04-03 18:42:45,836 INFO     |     add_p1_after_newln: False
2022-04-03 18:42:45,836 INFO     |     aggregate_micro: False
2022-04-03 18:42:45,836 INFO     |     allow_missing_init_opts: False
2022-04-03 18:42:45,836 INFO     |     batchsize: 1
2022-04-03 18:42:45,836 INFO     |     beam_block_full_context: True
2022-04-03 18:42:45,836 INFO     |     beam_block_list_filename: None
2022-04-03 18:42:45,836 INFO     |     beam_block_ngram: -1
2022-04-03 18:42:45,836 INFO     |     beam_context_block_ngram: -1
2022-04-03 18:42:45,836 INFO     |     beam_delay: 30
2022-04-03 18:42:45,836 INFO     |     beam_length_penalty: 0.65
2022-04-03 18:42:45,836 INFO     |     beam_min_length: 1
2022-04-03 18:42:45,836 INFO     |     beam_size: 1
2022-04-03 18:42:45,836 INFO     |     betas: '(0.9, 0.999)'
2022-04-03 18:42:45,836 INFO     |     bpe_add_prefix_space: None
2022-04-03 18:42:45,836 INFO     |     bpe_debug: False
2022-04-03 18:42:45,836 INFO     |     bpe_dropout: None
2022-04-03 18:42:45,836 INFO     |     bpe_merge: None
2022-04-03 18:42:45,836 INFO     |     bpe_vocab: None
2022-04-03 18:42:45,836 INFO     |     chosen_topic_delimiter: '\n'
2022-04-03 18:42:45,836 INFO     |     compute_tokenized_bleu: False
2022-04-03 18:42:45,836 INFO     |     datapath: /mnt/lustre/zhaojianqiao/ParlAI/data
2022-04-03 18:42:45,836 INFO     |     datatype: train
2022-04-03 18:42:45,836 INFO     |     ddp_backend: zero2
2022-04-03 18:42:45,836 INFO     |     delimiter: '\n'
2022-04-03 18:42:45,836 INFO     |     dict_class: parlai.core.dict:DictionaryAgent
2022-04-03 18:42:45,836 INFO     |     dict_endtoken: __end__
2022-04-03 18:42:45,836 INFO     |     dict_file: ft-hf-t5-11b/t5-11b.dict
2022-04-03 18:42:45,836 INFO     |     dict_include_test: False
2022-04-03 18:42:45,836 INFO     |     dict_include_valid: False
2022-04-03 18:42:45,836 INFO     |     dict_initpath: None
2022-04-03 18:42:45,836 INFO     |     dict_language: english
2022-04-03 18:42:45,837 INFO     |     dict_lower: False
2022-04-03 18:42:45,837 INFO     |     dict_max_ngram_size: -1
2022-04-03 18:42:45,837 INFO     |     dict_maxexs: -1
2022-04-03 18:42:45,837 INFO     |     dict_maxtokens: -1
2022-04-03 18:42:45,837 INFO     |     dict_minfreq: 0
2022-04-03 18:42:45,837 INFO     |     dict_nulltoken: __null__
2022-04-03 18:42:45,837 INFO     |     dict_starttoken: __start__
2022-04-03 18:42:45,837 INFO     |     dict_textfields: text,labels
2022-04-03 18:42:45,837 INFO     |     dict_tokenizer: re
2022-04-03 18:42:45,837 INFO     |     dict_unktoken: __unk__
2022-04-03 18:42:45,837 INFO     |     display_examples: False
2022-04-03 18:42:45,837 INFO     |     distributed_world_size: 4
2022-04-03 18:42:45,837 INFO     |     download_path: None
2022-04-03 18:42:45,837 INFO     |     dynamic_batching: None
2022-04-03 18:42:45,837 INFO     |     embedding_projection: random
2022-04-03 18:42:45,837 INFO     |     embedding_type: random
2022-04-03 18:42:45,837 INFO     |     eval_batchsize: None
2022-04-03 18:42:45,837 INFO     |     eval_dynamic_batching: None
2022-04-03 18:42:45,837 INFO     |     evaltask: None
2022-04-03 18:42:45,837 INFO     |     final_extra_opt:
2022-04-03 18:42:45,837 INFO     |     force_fp16_tokens: False
2022-04-03 18:42:45,837 INFO     |     fp16: True
2022-04-03 18:42:45,837 INFO     |     fp16_impl: safe
2022-04-03 18:42:45,837 INFO     |     gold_knowledge_delimiter: '\n'
2022-04-03 18:42:45,837 INFO     |     gpu: 0
2022-04-03 18:42:45,837 INFO     |     gradient_clip: 0.1
2022-04-03 18:42:45,837 INFO     |     hide_labels: False
2022-04-03 18:42:45,837 INFO     |     history_add_global_end_token: None
2022-04-03 18:42:45,837 INFO     |     history_reversed: False
2022-04-03 18:42:45,837 INFO     |     history_size: -1
2022-04-03 18:42:45,837 INFO     |     ignorant_dropout: 0.0
2022-04-03 18:42:45,837 INFO     |     image_cropsize: 224
2022-04-03 18:42:45,837 INFO     |     image_mode: raw
2022-04-03 18:42:45,837 INFO     |     image_size: 256
2022-04-03 18:42:45,837 INFO     |     include_checked_sentence: True
2022-04-03 18:42:45,837 INFO     |     include_knowledge: True
2022-04-03 18:42:45,837 INFO     |     include_knowledge_separator: True
2022-04-03 18:42:45,837 INFO     |     inference: greedy
2022-04-03 18:42:45,837 INFO     |     init_model: None
2022-04-03 18:42:45,837 INFO     |     init_opt: None
2022-04-03 18:42:45,837 INFO     |     interactive_mode: False
2022-04-03 18:42:45,837 INFO     |     invsqrt_lr_decay_gamma: -1
2022-04-03 18:42:45,837 INFO     |     is_debug: False
2022-04-03 18:42:45,837 INFO     |     label_truncate: None
2022-04-03 18:42:45,838 INFO     |     label_type: response
2022-04-03 18:42:45,838 INFO     |     learningrate: 5e-05
2022-04-03 18:42:45,838 INFO     |     load_from_checkpoint: True
2022-04-03 18:42:45,838 INFO     |     log_every_n_secs: -1
2022-04-03 18:42:45,838 INFO     |     log_every_n_steps: 50
2022-04-03 18:42:45,838 INFO     |     loglevel: info
2022-04-03 18:42:45,838 INFO     |     lr_scheduler: invsqrt
2022-04-03 18:42:45,838 INFO     |     lr_scheduler_decay: 0.5
2022-04-03 18:42:45,838 INFO     |     lr_scheduler_patience: 3
2022-04-03 18:42:45,838 INFO     |     max_train_steps: 200000
2022-04-03 18:42:45,838 INFO     |     max_train_time: -1
2022-04-03 18:42:45,838 INFO     |     metrics: default
2022-04-03 18:42:45,838 INFO     |     model: hugging_face/t5
2022-04-03 18:42:45,838 INFO     |     model_file: ft-hf-t5-11b/t5-11b
2022-04-03 18:42:45,838 INFO     |     momentum: 0
2022-04-03 18:42:45,838 INFO     |     multiprocessing: True
2022-04-03 18:42:45,838 INFO     |     multitask_weights: [1]
2022-04-03 18:42:45,838 INFO     |     mutators: None
2022-04-03 18:42:45,838 INFO     |     nesterov: True
2022-04-03 18:42:45,838 INFO     |     no_cuda: False
2022-04-03 18:42:45,838 INFO     |     num_epochs: -1
2022-04-03 18:42:45,838 INFO     |     num_topics: 5
2022-04-03 18:42:45,838 INFO     |     num_workers: 0
2022-04-03 18:42:45,838 INFO     |     nus: (0.7,)
2022-04-03 18:42:45,838 INFO     |     only_checked_knowledge: False
2022-04-03 18:42:45,838 INFO     |     optimizer: adam
2022-04-03 18:42:45,838 INFO     |     override: "{'add_missing_turns': 'all', 't5_model_arch': 't5-11b', 't5_model_parallel': False, 'fp16': True, 'optimizer': 'adam', 'lr_scheduler': 'invsqrt', 'warmup_updates': 1000, 'max_train_steps': 200000, 'betas': (0.9, 0.999), 'update_freq': 8, 'skip_generation': True, 'truncate': 8, 'ddp_backend': 'zero2', 'model_file': 'ft-hf-t5-11b/t5-11b', 'gpu': 0}"
2022-04-03 18:42:45,838 INFO     |     parlai_home: /mnt/lustre/zhaojianqiao/ParlAI
2022-04-03 18:42:45,838 INFO     |     person_tokens: False
2022-04-03 18:42:45,838 INFO     |     port: None
2022-04-03 18:42:45,838 INFO     |     prepend_gold_knowledge: False
2022-04-03 18:42:45,838 INFO     |     rank: 0
2022-04-03 18:42:45,838 INFO     |     rank_candidates: False
2022-04-03 18:42:45,838 INFO     |     save_after_valid: False
2022-04-03 18:42:45,838 INFO     |     save_every_n_secs: -1
2022-04-03 18:42:45,838 INFO     |     short_final_eval: False
2022-04-03 18:42:45,838 INFO     |     skip_generation: True
2022-04-03 18:42:45,838 INFO     |     special_tok_lst: None
2022-04-03 18:42:45,838 INFO     |     split_lines: False
2022-04-03 18:42:45,838 INFO     |     starttime: Apr03_18-36
2022-04-03 18:42:45,838 INFO     |     t5_dropout: 0.0
2022-04-03 18:42:45,838 INFO     |     t5_generation_config: None
2022-04-03 18:42:45,838 INFO     |     t5_model_arch: t5-11b
2022-04-03 18:42:45,839 INFO     |     t5_model_parallel: False
2022-04-03 18:42:45,839 INFO     |     task: wizard_of_wikipedia:generator
2022-04-03 18:42:45,839 INFO     |     temperature: 1.0
2022-04-03 18:42:45,839 INFO     |     tensorboard_log: False
2022-04-03 18:42:45,839 INFO     |     tensorboard_logdir: None
2022-04-03 18:42:45,839 INFO     |     text_truncate: None
2022-04-03 18:42:45,839 INFO     |     topk: 10
2022-04-03 18:42:45,839 INFO     |     topp: 0.9
2022-04-03 18:42:45,839 INFO     |     truncate: 8
2022-04-03 18:42:45,839 INFO     |     update_freq: 8
2022-04-03 18:42:45,839 INFO     |     use_reply: label
2022-04-03 18:42:45,839 INFO     |     validation_cutoff: 1.0
2022-04-03 18:42:45,839 INFO     |     validation_every_n_epochs: -1
2022-04-03 18:42:45,839 INFO     |     validation_every_n_secs: -1
2022-04-03 18:42:45,839 INFO     |     validation_every_n_steps: 1000
2022-04-03 18:42:45,839 INFO     |     validation_max_exs: -1
2022-04-03 18:42:45,839 INFO     |     validation_metric: ppl
2022-04-03 18:42:45,839 INFO     |     validation_metric_mode: min
2022-04-03 18:42:45,839 INFO     |     validation_patience: 15
2022-04-03 18:42:45,839 INFO     |     validation_share_agent: False
2022-04-03 18:42:45,839 INFO     |     verbose: False
2022-04-03 18:42:45,839 INFO     |     wandb_entity: None
2022-04-03 18:42:45,839 INFO     |     wandb_log: False
2022-04-03 18:42:45,839 INFO     |     wandb_name: None
2022-04-03 18:42:45,839 INFO     |     wandb_project: None
2022-04-03 18:42:45,839 INFO     |     warmup_rate: 0.0001
2022-04-03 18:42:45,839 INFO     |     warmup_updates: 1000
2022-04-03 18:42:45,839 INFO     |     weight_decay: None
2022-04-03 18:42:45,935 INFO     | Current ParlAI commit: b3da58c54cdeef366bcf6aeb11e41ee5652b7d28
2022-04-03 18:42:46,115 INFO     | creating task(s): wizard_of_wikipedia:generator
loading: /mnt/lustre/zhaojianqiao/ParlAI/data/wizard_of_wikipedia/train.json
2022-04-03 18:44:12,938 INFO     | training...
2022-04-03 18:44:12,981 WARNING  | parlai.tasks.wizard_of_wikipedia.agents.GeneratorTeacher' is outputting dicts instead of messages. If this is a teacher that is part of ParlAI, please file an issue on GitHub. If it is your own teacher, please return a Message object instead.
2022-04-03 18:44:26,023 ERROR    | Ran out of memory, skipping batch. if this happens frequently, decrease batchsize or truncate the inputs to the model.
rank:  2 | 2022-04-03 18:44:26,023 ERROR    | Ran out of memory, skipping batch. if this happens frequently, decrease batchsize or truncate the inputs to the model.
rank:  3 | 2022-04-03 18:44:26,024 ERROR    | Ran out of memory, skipping batch. if this happens frequently, decrease batchsize or truncate the inputs to the model.
rank:  1 | 2022-04-03 18:44:26,026 ERROR    | Ran out of memory, skipping batch. if this happens frequently, decrease batchsize or truncate the inputs to the model.
rank:  3 | 2022-04-03 18:44:26,615 CRITICAL | Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 605, in _fake_forward_backward_pass
    self.backward(loss)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2314, in backward
    self.optimizer.backward(loss, update_main_grads=False)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/utils/fp16.py", line 194, in backward
    loss.backward()
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 21.06 GiB (GPU 3; 79.35 GiB total capacity; 63.19 GiB already allocated; 8.57 GiB free; 68.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/multiprocessing_train.py", line 45, in multiprocess_train
    return single_train.TrainLoop(opt).train()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 950, in train
    for _train_log in self.train_steps():
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 857, in train_steps
    world.parley()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/worlds.py", line 370, in parley
    acts[1] = agents[1].act()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 759, in train_step
    self._fake_forward_backward_pass()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 614, in _fake_forward_backward_pass
    raise RuntimeError(m)
RuntimeError: CUDA OOM: Lower batch size (-bs) from 1 or lower  max sequence length (-tr) from 8

rank:  1 | 2022-04-03 18:44:26,615 CRITICAL | Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 605, in _fake_forward_backward_pass
    self.backward(loss)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2314, in backward
    self.optimizer.backward(loss, update_main_grads=False)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/utils/fp16.py", line 194, in backward
    loss.backward()
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 21.06 GiB (GPU 1; 79.35 GiB total capacity; 63.19 GiB already allocated; 8.44 GiB free; 68.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/multiprocessing_train.py", line 45, in multiprocess_train
    return single_train.TrainLoop(opt).train()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 950, in train
    for _train_log in self.train_steps():
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 857, in train_steps
    world.parley()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/worlds.py", line 370, in parley
    acts[1] = agents[1].act()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 759, in train_step
    self._fake_forward_backward_pass()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 614, in _fake_forward_backward_pass
    raise RuntimeError(m)
RuntimeError: CUDA OOM: Lower batch size (-bs) from 1 or lower  max sequence length (-tr) from 8

2022-04-03 18:44:26,615 CRITICAL | Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 605, in _fake_forward_backward_pass
    self.backward(loss)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2314, in backward
    self.optimizer.backward(loss, update_main_grads=False)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/utils/fp16.py", line 194, in backward
    loss.backward()
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 21.06 GiB (GPU 0; 79.35 GiB total capacity; 63.19 GiB already allocated; 8.57 GiB free; 68.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/multiprocessing_train.py", line 45, in multiprocess_train
    return single_train.TrainLoop(opt).train()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 950, in train
    for _train_log in self.train_steps():
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 857, in train_steps
    world.parley()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/worlds.py", line 370, in parley
    acts[1] = agents[1].act()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 759, in train_step
    self._fake_forward_backward_pass()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 614, in _fake_forward_backward_pass
    raise RuntimeError(m)
RuntimeError: CUDA OOM: Lower batch size (-bs) from 1 or lower  max sequence length (-tr) from 8

rank:  2 | 2022-04-03 18:44:26,616 CRITICAL | Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 605, in _fake_forward_backward_pass
    self.backward(loss)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2314, in backward
    self.optimizer.backward(loss, update_main_grads=False)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/utils/fp16.py", line 194, in backward
    loss.backward()
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/mnt/lustre/zhaojianqiao/anaconda3/envs/parlai/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 21.06 GiB (GPU 2; 79.35 GiB total capacity; 63.19 GiB already allocated; 8.44 GiB free; 68.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/multiprocessing_train.py", line 45, in multiprocess_train
    return single_train.TrainLoop(opt).train()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 950, in train
    for _train_log in self.train_steps():
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/scripts/train_model.py", line 857, in train_steps
    world.parley()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/worlds.py", line 370, in parley
    acts[1] = agents[1].act()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2143, in act
    response = self.batch_act([self.observation])[0]
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_agent.py", line 2234, in batch_act
    output = self.train_step(batch)
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 759, in train_step
    self._fake_forward_backward_pass()
  File "/mnt/lustre/zhaojianqiao/ParlAI/parlai/core/torch_generator_agent.py", line 614, in _fake_forward_backward_pass
    raise RuntimeError(m)
RuntimeError: CUDA OOM: Lower batch size (-bs) from 1 or lower  max sequence length (-tr) from 8

rank:  3 | 2022-04-03 18:44:26,618 CRITICAL | Got the above exception on worker 3. This may cause hangs requiring manual killing of processes.
rank:  1 | 2022-04-03 18:44:26,618 CRITICAL | Got the above exception on worker 1. This may cause hangs requiring manual killing of processes.
2022-04-03 18:44:26,618 CRITICAL | Got the above exception on worker 0. This may cause hangs requiring manual killing of processes.
rank:  2 | 2022-04-03 18:44:26,618 CRITICAL | Got the above exception on worker 2. This may cause hangs requiring manual killing of processes.
```

**Comment by stephenroller** [comment]
So the fewer reported parameters is indeed expected -- it's a display bug as a result of the sharding.

I wonder if fp16 really is being used.... 320gb of vram is a lot.

**Comment by lyy1994** [comment]
I am pretty sure that I add `--fp16 True` in the command, but I don't know what really happened internally.

**Comment by stephenroller** [comment]
Those look like hardware failures to me. Which is highly consistent with my personal experiences with A100s...

**Comment by stephenroller** [comment]
Side note: someone at FAIR has found a tentative fix to reduce memory pressure of FSDP. Should be a nice lift here too
