### ISSUE TITLE
BlenderBot 3 30B. CUDA out of memory.

### ISSUE THREAD

**Issue by guialfaro053** [facebookresearch/ParlAI#4772]
**Bug description**
Hello, I have been trying to run BlenderBot 3 30B and I keep getting the same problem. When I run `metaseq-api-local`, CUDA runs out of memory but when I try to reduce the number of batches, the same error keeps popping up regardless of the batch size.
These are my parameters on the `constants.py` file:

`MAX_SEQ_LEN = 1024
BATCH_SIZE = 64  # silly high bc we dynamically batch by MAX_BATCH_TOKENS
MAX_BATCH_TOKENS = 1024
DEFAULT_PORT = 6010 
MODEL_PARALLEL = 4
TOTAL_WORLD_SIZE = 4
MAX_BEAM = 8`

I am currently using 4 T4 GPUs on GCP. 

**Reproduction steps**

1. Modify the `constants.py` file as shown above
2. Run `metaseq-api-local` 

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```

RuntimeError: CUDA out of memory. Tried to allocate 296.00 MiB (GPU 0; 14.62 GiB total capacity; 13.69 GiB already allocated; 237.00 MiB free; 13.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

**Additional context**
I would really appreciate it if someone can indicate to me how to change such parameters so that I can run the model with the resources I have. Thank you

**Comment by klshuster** [comment]
you should probably set `MAX_BATCH_TOKENS` to 1 and `MAX_BEAM` to 1 as well.

Are you running with model parallel across all 4 gpus? or just the consolidated model?

**Comment by guialfaro053** [comment]
Thank you for your reply Kurt! I reran the code but now the error I get seems to be related to a state_dict for FlattenParamsWrapper.


```
2022-08-26 09:05:02 | INFO | metaseq.modules.fused_bias_gelu | Done with compiling and loading fused kernels.
Traceback (most recent call last):
  File "/home/Guillermo/anaconda3/envs/chatbots/bin/metaseq-api-local", line 8, in <module>
    sys.exit(cli_main())
  File "/home/Guillermo/metaseq/metaseq_cli/interactive_hosted.py", line 363, in cli_main
    distributed_utils.call_main(cfg, worker_main, namespace_args=args)
  File "/home/Guillermo/metaseq/metaseq/distributed/utils.py", line 270, in call_main
    return _spawn_helper(main, cfg, kwargs)
  File "/home/Guillermo/metaseq/metaseq/distributed/utils.py", line 248, in _spawn_helper
    retval = distributed_main(-1, main, cfg, kwargs)
  File "/home/Guillermo/metaseq/metaseq/distributed/utils.py", line 210, in distributed_main
    retval = main(cfg, **kwargs)
  File "/home/Guillermo/metaseq/metaseq_cli/interactive_hosted.py", line 176, in worker_main
    models = generator.load_model()  # noqa: F841
  File "/home/Guillermo/metaseq/metaseq/hub_utils.py", line 507, in load_model
    models, _model_args, _task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/Guillermo/metaseq/metaseq/checkpoint_utils.py", line 515, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict)
  File "/home/Guillermo/metaseq/metaseq/distributed/fully_sharded_data_parallel.py", line 76, in load_state_dict
    return super().load_local_state_dict(state_dict, strict=strict)
  File "/home/Guillermo/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 827, in load_local_state_dict
    output = self._load_state_dict(state_dict, strict)
  File "/home/Guillermo/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 811, in _load_state_dict
    return self.module.load_state_dict(state_dict, strict)
  File "/home/Guillermo/fairscale/fairscale/nn/misc/flatten_params_wrapper.py", line 449, in load_state_dict
    return super().load_state_dict(state_dict, strict)
  File "/home/Guillermo/anaconda3/envs/chatbots/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FlattenParamsWrapper:
        Missing key(s) in state_dict: "_fpw_module.decoder.layers.0._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.1._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.2._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.3._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.4._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.5._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.6._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.7._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.8._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.9._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.10._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.11._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.12._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.13._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.14._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.15._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.16._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.17._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.18._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.19._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.20._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.21._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.22._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.23._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.24._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.25._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.26._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.27._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.28._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.29._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.30._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.31._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.32._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.33._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.34._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.35._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.36._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.37._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.38._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.39._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.40._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.41._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.42._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.43._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.44._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.45._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.46._fsdp_wrapped_module.flat_param_0", "_fpw_module.decoder.layers.47._fsdp_wrapped_module.flat_param_0".
        Unexpected key(s) in state_dict: "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.0._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.1._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.2._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.3._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.4._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.5._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.6._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.7._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.8._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.9._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.10._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.11._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.12._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.13._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.14._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.15._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.16._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.17._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.18._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.19._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.20._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.21._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.22._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.23._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.24._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.25._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.26._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.27._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.28._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.29._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.30._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.31._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.32._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.33._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.34._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.35._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.36._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.37._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.38._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.39._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.40._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.41._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.42._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.43._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.44._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.45._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.46._fsdp_wrapped_module._fpw_module.final_layer_norm.bias", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.weight", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.self_attn.qkv_proj.bias", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.self_attn.out_proj.weight", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.self_attn.out_proj.bias", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.weight", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.self_attn_layer_norm.bias", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.fc1.weight", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.fc1.bias", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.fc2.weight", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.fc2.bias", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.final_layer_norm.weight", "_fpw_module.decoder.layers.47._fsdp_wrapped_module._fpw_module.final_layer_norm.bias".
```

I checked the name of the parameters of the `reshard-model_part0.pt` and they are the same as the ones above but without the _fwp and ._fsdp_wrapped part. 

My constants file is: 

```
MAX_SEQ_LEN = 1024
BATCH_SIZE = 512  # silly high bc we dynamically batch by MAX_BATCH_TOKENS
MAX_BATCH_TOKENS = 3072
DEFAULT_PORT = 6010
MODEL_PARALLEL = 2
TOTAL_WORLD_SIZE = 2
MAX_BEAM = 8

....


LAUNCH_ARGS = [
    f"--model-parallel-size {MODEL_PARALLEL}",
    f"--distributed-world-size {TOTAL_WORLD_SIZE}",
    "--task language_modeling",
    f"--bpe-merges {BPE_MERGES}",
    f"--bpe-vocab {BPE_VOCAB}",
    "--bpe hf_byte_bpe",
    f"--merges-filename {BPE_MERGES}",  # TODO(susanz): hack for getting interactive_hosted working on public repo
    f"--vocab-filename {BPE_VOCAB}",  # TODO(susanz): hack for getting interactive_hosted working on public repo
    f"--path {CHECKPOINT_FOLDER}/reshard.pt",
    "--beam 1 --nbest 1",
    "--distributed-port -1",
    "--checkpoint-shard-count 1",
    "--use-sharded-state",
    f"--batch-size {BATCH_SIZE}",
    f"--buffer-size {BATCH_SIZE * MAX_SEQ_LEN}",
    f"--max-tokens {BATCH_SIZE * MAX_SEQ_LEN}",
    "/tmp",  # required "data" argument.
]

**Comment by klshuster** [comment]
assuming you used the `reshard_model_parallel` script, pull in these changes to your metaseq checkout: https://github.com/facebookresearch/metaseq/pull/170. that should fix the problem

**Comment by guialfaro053** [comment]
That solves the error and it works nicely! Thank you :)

**Comment by guialfaro053** [comment]
> also, if you're using 4 gpus, I recommend resharding into model parallel 4 (and then modifying constants appropriately)

Hey Kurt, quick question even though I closed the issue. Is it possible to:

1. Run BB3 with 2 GPUs and 4 checkpoints?
2. Run BB3 with 4 GPUs and 2 checkpoints?

Has `MODEL_PARALLEL` to be same as `TOTAL_WORLD_SIZE`? I am new to sharded data parallel and resharding so I was curious.

**Comment by klshuster** [comment]
With the way that metaseq is set up, each sharded checkpoint file will be loaded onto a single GPU. So, I'm not totally sure the situations you listed above are possible in the current setup. model parallel does not necessarily need to be same as total world size - there is a way to run the model with e.g. the model parallel + fully-sharded data parallel shards, but that is not recommended (FSDP during inference is quite slow due to node communication latency)
